# -*- coding: utf-8 -*-
"""IrisAi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ULcjFcdPqYfnO6BqQ45mDvUvFpPXzLAe
"""

#DATA EXPLORATION
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize']=(4,4)
data = pd.read_csv('https://raw.githubusercontent.com/Adithya-Suresh/iris-/master/Iris.csv')
print(data.head(10))
print(data.info())
print(data.describe())

#DATA ANALYSIS AND PREPROCESS
data.plot.scatter(x='SepalLengthCm',y='SepalWidthCm')
data.plot.scatter(x='PetalLengthCm',y='PetalWidthCm')
dte=data
dte=dte.drop(dte.index[dte.SepalLengthCm>=7.0],axis=0)

dte=dte.drop(dte.index[dte.SepalWidthCm>=3.5],axis=0)
dte.plot.scatter(x='SepalLengthCm',y='SepalWidthCm')
dte.plot.scatter(x='PetalLengthCm',y='PetalWidthCm')
print(dte.describe())

d=pd.DataFrame(dte)
d=d.drop(['Id'],axis=1)
X=d
X=X.drop(['Species'],axis=1)
y=d['Species'].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=7,p=2,metric="minkowski")
classifier.fit(X_train,y_train)
y_p=classifier.predict(X_test)
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_p)
print(acc)

x=classifier.predict([[7.6,3,6.6,0.6]])
print(x)